//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CowSite.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FeedInfo", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class FeedInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int feidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float felengField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fenameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fetdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int jidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int jrankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jstatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ttidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int feid {
            get {
                return this.feidField;
            }
            set {
                if ((this.feidField.Equals(value) != true)) {
                    this.feidField = value;
                    this.RaisePropertyChanged("feid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float feleng {
            get {
                return this.felengField;
            }
            set {
                if ((this.felengField.Equals(value) != true)) {
                    this.felengField = value;
                    this.RaisePropertyChanged("feleng");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fename {
            get {
                return this.fenameField;
            }
            set {
                if ((object.ReferenceEquals(this.fenameField, value) != true)) {
                    this.fenameField = value;
                    this.RaisePropertyChanged("fename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fetdate {
            get {
                return this.fetdateField;
            }
            set {
                if ((this.fetdateField.Equals(value) != true)) {
                    this.fetdateField = value;
                    this.RaisePropertyChanged("fetdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int jid {
            get {
                return this.jidField;
            }
            set {
                if ((this.jidField.Equals(value) != true)) {
                    this.jidField = value;
                    this.RaisePropertyChanged("jid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int jrank {
            get {
                return this.jrankField;
            }
            set {
                if ((this.jrankField.Equals(value) != true)) {
                    this.jrankField = value;
                    this.RaisePropertyChanged("jrank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jstat {
            get {
                return this.jstatField;
            }
            set {
                if ((object.ReferenceEquals(this.jstatField, value) != true)) {
                    this.jstatField = value;
                    this.RaisePropertyChanged("jstat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int stid {
            get {
                return this.stidField;
            }
            set {
                if ((this.stidField.Equals(value) != true)) {
                    this.stidField = value;
                    this.RaisePropertyChanged("stid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ttid {
            get {
                return this.ttidField;
            }
            set {
                if ((this.ttidField.Equals(value) != true)) {
                    this.ttidField = value;
                    this.RaisePropertyChanged("ttid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FeedCowInfo", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class FeedCowInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int csidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string csnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int flintField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double flweigField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int csid {
            get {
                return this.csidField;
            }
            set {
                if ((this.csidField.Equals(value) != true)) {
                    this.csidField = value;
                    this.RaisePropertyChanged("csid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string csname {
            get {
                return this.csnameField;
            }
            set {
                if ((object.ReferenceEquals(this.csnameField, value) != true)) {
                    this.csnameField = value;
                    this.RaisePropertyChanged("csname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int flint {
            get {
                return this.flintField;
            }
            set {
                if ((this.flintField.Equals(value) != true)) {
                    this.flintField = value;
                    this.RaisePropertyChanged("flint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double flweig {
            get {
                return this.flweigField;
            }
            set {
                if ((this.flweigField.Equals(value) != true)) {
                    this.flweigField = value;
                    this.RaisePropertyChanged("flweig");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobInfo", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class JobInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ctidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int foidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jauthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime jdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int jidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float jlengField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string joperField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int jrankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jstatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int jtbatcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime jtdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jtypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int trmidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ctid {
            get {
                return this.ctidField;
            }
            set {
                if ((this.ctidField.Equals(value) != true)) {
                    this.ctidField = value;
                    this.RaisePropertyChanged("ctid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int foid {
            get {
                return this.foidField;
            }
            set {
                if ((this.foidField.Equals(value) != true)) {
                    this.foidField = value;
                    this.RaisePropertyChanged("foid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jauth {
            get {
                return this.jauthField;
            }
            set {
                if ((object.ReferenceEquals(this.jauthField, value) != true)) {
                    this.jauthField = value;
                    this.RaisePropertyChanged("jauth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime jdate {
            get {
                return this.jdateField;
            }
            set {
                if ((this.jdateField.Equals(value) != true)) {
                    this.jdateField = value;
                    this.RaisePropertyChanged("jdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int jid {
            get {
                return this.jidField;
            }
            set {
                if ((this.jidField.Equals(value) != true)) {
                    this.jidField = value;
                    this.RaisePropertyChanged("jid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float jleng {
            get {
                return this.jlengField;
            }
            set {
                if ((this.jlengField.Equals(value) != true)) {
                    this.jlengField = value;
                    this.RaisePropertyChanged("jleng");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jname {
            get {
                return this.jnameField;
            }
            set {
                if ((object.ReferenceEquals(this.jnameField, value) != true)) {
                    this.jnameField = value;
                    this.RaisePropertyChanged("jname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string joper {
            get {
                return this.joperField;
            }
            set {
                if ((object.ReferenceEquals(this.joperField, value) != true)) {
                    this.joperField = value;
                    this.RaisePropertyChanged("joper");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int jrank {
            get {
                return this.jrankField;
            }
            set {
                if ((this.jrankField.Equals(value) != true)) {
                    this.jrankField = value;
                    this.RaisePropertyChanged("jrank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jstat {
            get {
                return this.jstatField;
            }
            set {
                if ((object.ReferenceEquals(this.jstatField, value) != true)) {
                    this.jstatField = value;
                    this.RaisePropertyChanged("jstat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int jtbatc {
            get {
                return this.jtbatcField;
            }
            set {
                if ((this.jtbatcField.Equals(value) != true)) {
                    this.jtbatcField = value;
                    this.RaisePropertyChanged("jtbatc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime jtdate {
            get {
                return this.jtdateField;
            }
            set {
                if ((this.jtdateField.Equals(value) != true)) {
                    this.jtdateField = value;
                    this.RaisePropertyChanged("jtdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jtype {
            get {
                return this.jtypeField;
            }
            set {
                if ((object.ReferenceEquals(this.jtypeField, value) != true)) {
                    this.jtypeField = value;
                    this.RaisePropertyChanged("jtype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pid {
            get {
                return this.pidField;
            }
            set {
                if ((this.pidField.Equals(value) != true)) {
                    this.pidField = value;
                    this.RaisePropertyChanged("pid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int trmid {
            get {
                return this.trmidField;
            }
            set {
                if ((this.trmidField.Equals(value) != true)) {
                    this.trmidField = value;
                    this.RaisePropertyChanged("trmid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobIngreForageInfo", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class JobIngreForageInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int fidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int jidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int jiintField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float jiweigField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int fid {
            get {
                return this.fidField;
            }
            set {
                if ((this.fidField.Equals(value) != true)) {
                    this.fidField = value;
                    this.RaisePropertyChanged("fid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fname {
            get {
                return this.fnameField;
            }
            set {
                if ((object.ReferenceEquals(this.fnameField, value) != true)) {
                    this.fnameField = value;
                    this.RaisePropertyChanged("fname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int jid {
            get {
                return this.jidField;
            }
            set {
                if ((this.jidField.Equals(value) != true)) {
                    this.jidField = value;
                    this.RaisePropertyChanged("jid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int jiint {
            get {
                return this.jiintField;
            }
            set {
                if ((this.jiintField.Equals(value) != true)) {
                    this.jiintField = value;
                    this.RaisePropertyChanged("jiint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float jiweig {
            get {
                return this.jiweigField;
            }
            set {
                if ((this.jiweigField.Equals(value) != true)) {
                    this.jiweigField = value;
                    this.RaisePropertyChanged("jiweig");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FeedModel", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class FeedModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string feauthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int feidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fenameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fetdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int jrankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ttidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string feauth {
            get {
                return this.feauthField;
            }
            set {
                if ((object.ReferenceEquals(this.feauthField, value) != true)) {
                    this.feauthField = value;
                    this.RaisePropertyChanged("feauth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int feid {
            get {
                return this.feidField;
            }
            set {
                if ((this.feidField.Equals(value) != true)) {
                    this.feidField = value;
                    this.RaisePropertyChanged("feid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fename {
            get {
                return this.fenameField;
            }
            set {
                if ((object.ReferenceEquals(this.fenameField, value) != true)) {
                    this.fenameField = value;
                    this.RaisePropertyChanged("fename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fetdate {
            get {
                return this.fetdateField;
            }
            set {
                if ((this.fetdateField.Equals(value) != true)) {
                    this.fetdateField = value;
                    this.RaisePropertyChanged("fetdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int jrank {
            get {
                return this.jrankField;
            }
            set {
                if ((this.jrankField.Equals(value) != true)) {
                    this.jrankField = value;
                    this.RaisePropertyChanged("jrank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int stid {
            get {
                return this.stidField;
            }
            set {
                if ((this.stidField.Equals(value) != true)) {
                    this.stidField = value;
                    this.RaisePropertyChanged("stid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ttid {
            get {
                return this.ttidField;
            }
            set {
                if ((this.ttidField.Equals(value) != true)) {
                    this.ttidField = value;
                    this.RaisePropertyChanged("ttid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFeedInfoList", ReplyAction="http://tempuri.org/IService1/GetFeedInfoListResponse")]
        CowSite.ServiceReference1.FeedInfo[] GetFeedInfoList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFeedInfoList", ReplyAction="http://tempuri.org/IService1/GetFeedInfoListResponse")]
        System.Threading.Tasks.Task<CowSite.ServiceReference1.FeedInfo[]> GetFeedInfoListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFeedCowInfoList", ReplyAction="http://tempuri.org/IService1/GetFeedCowInfoListResponse")]
        CowSite.ServiceReference1.FeedCowInfo[] GetFeedCowInfoList(int feid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFeedCowInfoList", ReplyAction="http://tempuri.org/IService1/GetFeedCowInfoListResponse")]
        System.Threading.Tasks.Task<CowSite.ServiceReference1.FeedCowInfo[]> GetFeedCowInfoListAsync(int feid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetjobInfo", ReplyAction="http://tempuri.org/IService1/GetjobInfoResponse")]
        CowSite.ServiceReference1.JobInfo[] GetjobInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetjobInfo", ReplyAction="http://tempuri.org/IService1/GetjobInfoResponse")]
        System.Threading.Tasks.Task<CowSite.ServiceReference1.JobInfo[]> GetjobInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetIngreForageInfo", ReplyAction="http://tempuri.org/IService1/GetIngreForageInfoResponse")]
        CowSite.ServiceReference1.JobIngreForageInfo[] GetIngreForageInfo(int jid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetIngreForageInfo", ReplyAction="http://tempuri.org/IService1/GetIngreForageInfoResponse")]
        System.Threading.Tasks.Task<CowSite.ServiceReference1.JobIngreForageInfo[]> GetIngreForageInfoAsync(int jid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProcessList", ReplyAction="http://tempuri.org/IService1/GetProcessListResponse")]
        CowSite.ServiceReference1.FeedModel[] GetProcessList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProcessList", ReplyAction="http://tempuri.org/IService1/GetProcessListResponse")]
        System.Threading.Tasks.Task<CowSite.ServiceReference1.FeedModel[]> GetProcessListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        CowSite.ServiceReference1.CompositeType GetDataUsingDataContract(CowSite.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<CowSite.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(CowSite.ServiceReference1.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : CowSite.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<CowSite.ServiceReference1.IService1>, CowSite.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CowSite.ServiceReference1.FeedInfo[] GetFeedInfoList() {
            return base.Channel.GetFeedInfoList();
        }
        
        public System.Threading.Tasks.Task<CowSite.ServiceReference1.FeedInfo[]> GetFeedInfoListAsync() {
            return base.Channel.GetFeedInfoListAsync();
        }
        
        public CowSite.ServiceReference1.FeedCowInfo[] GetFeedCowInfoList(int feid) {
            return base.Channel.GetFeedCowInfoList(feid);
        }
        
        public System.Threading.Tasks.Task<CowSite.ServiceReference1.FeedCowInfo[]> GetFeedCowInfoListAsync(int feid) {
            return base.Channel.GetFeedCowInfoListAsync(feid);
        }
        
        public CowSite.ServiceReference1.JobInfo[] GetjobInfo() {
            return base.Channel.GetjobInfo();
        }
        
        public System.Threading.Tasks.Task<CowSite.ServiceReference1.JobInfo[]> GetjobInfoAsync() {
            return base.Channel.GetjobInfoAsync();
        }
        
        public CowSite.ServiceReference1.JobIngreForageInfo[] GetIngreForageInfo(int jid) {
            return base.Channel.GetIngreForageInfo(jid);
        }
        
        public System.Threading.Tasks.Task<CowSite.ServiceReference1.JobIngreForageInfo[]> GetIngreForageInfoAsync(int jid) {
            return base.Channel.GetIngreForageInfoAsync(jid);
        }
        
        public CowSite.ServiceReference1.FeedModel[] GetProcessList() {
            return base.Channel.GetProcessList();
        }
        
        public System.Threading.Tasks.Task<CowSite.ServiceReference1.FeedModel[]> GetProcessListAsync() {
            return base.Channel.GetProcessListAsync();
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public CowSite.ServiceReference1.CompositeType GetDataUsingDataContract(CowSite.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<CowSite.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(CowSite.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
